basePath: /
host: 192.168.13.5:8080
info:
  contact:
    email: support@swagger.io
    name: API Support (Ashwani)
    url: http://www.swagger.io/support
  description: This is E-Commerce API Server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: APIs of E-Commerce Project
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - '*/*'
      description: get the all wishlist of the User.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Shows the all wishlist of the User.
      tags:
      - User
schemes:
- http
swagger: "2.0"
