// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support (Ashwani)",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/address": {
            "post": {
                "description": "To get address list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER"
                ],
                "summary": "Get all addresses of the User.",
                "parameters": [
                    {
                        "description": "It takes UserId",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userData.BodyUserIdInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/address.Address"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/c_wishlist": {
            "post": {
                "description": "To create wishlist of the User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER_ITEM"
                ],
                "summary": "Creates wishlist for selected product.",
                "parameters": [
                    {
                        "description": "It takes UserId, ProductId, Quantity",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userData.BodyWishlistInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userData.StatusMsg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cart_item": {
            "post": {
                "description": "To get cart list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER_ITEM"
                ],
                "summary": "Get all cart products of the User.",
                "parameters": [
                    {
                        "description": "It takes UserId",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userData.BodyUserIdInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cart_item.CartItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/createUser": {
            "post": {
                "description": "To create and save User Data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER"
                ],
                "summary": "Creates User .",
                "parameters": [
                    {
                        "description": "It takes UserId",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userData.BodyCreateUserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userData.StatusMsg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/d_wishlist": {
            "delete": {
                "description": "To delete the selected product from User's Wishlist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER_ITEM"
                ],
                "summary": "Deletes the selected wishlistId from the Wishlist Table.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "wishlist_id value",
                        "name": "wishlistId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userData.StatusMsg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ec": {
            "get": {
                "description": "To get Home's Views Group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VIEW_GROUP"
                ],
                "summary": "Provides HomePage Views Groups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ViewGroupMockResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/explore": {
            "get": {
                "description": "To get response of Explore Btn CTA",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VIEW_GROUP"
                ],
                "summary": "Explore Click To Action",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ViewGroupMockResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/getAllUsers": {
            "post": {
                "description": "To get all Users list (userId = 09876).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER"
                ],
                "summary": "Provides All Users.",
                "parameters": [
                    {
                        "description": "It takes UserId",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userData.BodyUserIdInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.User"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/onboarding": {
            "get": {
                "description": "To get response of OnBoarding Page ViewGroup",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VIEW_GROUP"
                ],
                "summary": "OnBoarding Page ViewGroup",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SubscriptionPageMockResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "description": "To get ProfilePage Views Group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VIEW_GROUP"
                ],
                "summary": "Provides ProfilePage Views Groups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/data.Profile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/r_wishlist": {
            "post": {
                "description": "Get the all wishlist of the User.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER_ITEM"
                ],
                "summary": "Shows the all wishlist of the User.",
                "parameters": [
                    {
                        "description": "It takes UserId",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userData.BodyUserIdInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/wishlist.Wishlist"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subscription": {
            "get": {
                "description": "To get response of Subscription Page ViewGroup",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VIEW_GROUP"
                ],
                "summary": "Subscription Page ViewGroup",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SubscriptionPageMockResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "To get subscription list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER_ITEM"
                ],
                "summary": "Get all subscribed products of the User.",
                "parameters": [
                    {
                        "description": "It takes UserId",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userData.BodyUserIdInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/subscriptions.Subscription"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "To get User's information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER"
                ],
                "summary": "Get User's information.",
                "parameters": [
                    {
                        "description": "It takes UserId",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userData.BodyUserIdInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "address.Address": {
            "type": "object",
            "properties": {
                "addressId": {
                    "type": "string"
                },
                "addressLine1": {
                    "type": "string"
                },
                "addressLine2": {
                    "type": "string"
                },
                "addressType": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "isPreferred": {
                    "type": "boolean"
                },
                "mobile1": {
                    "type": "string"
                },
                "mobile2": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "cart_item.CartItem": {
            "type": "object",
            "properties": {
                "cart_item_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "modified_at": {
                    "type": "string"
                },
                "product": {
                    "$ref": "#/definitions/products.Product"
                },
                "product_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "data.Action": {
            "type": "object",
            "properties": {
                "api": {
                    "type": "string"
                },
                "destination": {
                    "description": "Screen destination",
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "query": {
                    "description": "API Query",
                    "type": "string"
                }
            }
        },
        "data.Profile": {
            "type": "object",
            "properties": {
                "cta_profile": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.ProfileCta"
                    }
                },
                "profile_pic": {
                    "type": "string"
                },
                "user_email": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "data.ProfileCta": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/data.Action"
                },
                "title": {
                    "type": "string"
                },
                "value": {
                    "$ref": "#/definitions/data.Value"
                }
            }
        },
        "data.Value": {
            "type": "object",
            "properties": {
                "banner_1x": {
                    "type": "string"
                },
                "banner_2x": {
                    "type": "string"
                },
                "banner_3x": {
                    "type": "string"
                },
                "banner_4x": {
                    "type": "string"
                },
                "thumb_1x": {
                    "type": "string"
                },
                "thumb_2x": {
                    "type": "string"
                },
                "thumb_3x": {
                    "type": "string"
                },
                "thumb_4x": {
                    "type": "string"
                }
            }
        },
        "products.Product": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "2",
                    "type": "string"
                },
                "description": {
                    "description": "8",
                    "type": "string"
                },
                "dimension": {
                    "description": "3",
                    "type": "string"
                },
                "last_Updated": {
                    "description": "15",
                    "type": "string"
                },
                "manufacturer_id": {
                    "description": "4",
                    "type": "string"
                },
                "name": {
                    "description": "5",
                    "type": "string"
                },
                "picture": {
                    "description": "6",
                    "type": "string"
                },
                "price": {
                    "description": "7",
                    "type": "number"
                },
                "product_id": {
                    "description": "1",
                    "type": "string"
                },
                "seller_id": {
                    "description": "9",
                    "type": "string"
                },
                "seller_name": {
                    "description": "10",
                    "type": "string"
                },
                "sku": {
                    "description": "11",
                    "type": "string"
                },
                "sub_category_id": {
                    "description": "12",
                    "type": "string"
                },
                "subscribable": {
                    "description": "16",
                    "type": "boolean"
                },
                "units": {
                    "description": "14",
                    "type": "integer"
                },
                "weight": {
                    "description": "13",
                    "type": "number"
                }
            }
        },
        "response.SubscriptionPageMockResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "children": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "action": {
                                            "type": "object",
                                            "properties": {
                                                "api": {
                                                    "type": "string"
                                                },
                                                "destination": {
                                                    "type": "string"
                                                },
                                                "method": {
                                                    "type": "string"
                                                },
                                                "query": {
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "background_color": {
                                            "type": "object",
                                            "properties": {
                                                "alpha": {
                                                    "type": "integer"
                                                },
                                                "hue": {
                                                    "type": "integer"
                                                },
                                                "lighting": {
                                                    "type": "integer"
                                                },
                                                "saturation": {
                                                    "type": "integer"
                                                }
                                            }
                                        },
                                        "product_id": {
                                            "type": "string"
                                        },
                                        "product_info": {
                                            "type": "object",
                                            "properties": {
                                                "display_selling_scale": {
                                                    "type": "string"
                                                },
                                                "offer_percentage": {
                                                    "type": "string"
                                                },
                                                "offer_price": {
                                                    "type": "integer"
                                                },
                                                "quantity": {
                                                    "type": "integer"
                                                },
                                                "unit_price": {
                                                    "type": "integer"
                                                }
                                            }
                                        },
                                        "subscription_info": {
                                            "type": "object",
                                            "properties": {
                                                "created_at": {
                                                    "type": "string"
                                                },
                                                "end_date": {
                                                    "type": "string"
                                                },
                                                "friday": {
                                                    "type": "boolean"
                                                },
                                                "monday": {
                                                    "type": "boolean"
                                                },
                                                "order_id": {
                                                    "type": "string"
                                                },
                                                "pause_dates": {
                                                    "type": "string"
                                                },
                                                "product_id": {
                                                    "type": "string"
                                                },
                                                "saturday": {
                                                    "type": "boolean"
                                                },
                                                "start_date": {
                                                    "type": "string"
                                                },
                                                "subscription_id": {
                                                    "type": "string"
                                                },
                                                "sunday": {
                                                    "type": "boolean"
                                                },
                                                "thursday": {
                                                    "type": "boolean"
                                                },
                                                "tuesday": {
                                                    "type": "boolean"
                                                },
                                                "user_id": {
                                                    "type": "string"
                                                },
                                                "wednesday": {
                                                    "type": "boolean"
                                                }
                                            }
                                        },
                                        "title": {
                                            "type": "string"
                                        },
                                        "type": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "object",
                                            "properties": {
                                                "banner_1x": {
                                                    "type": "string"
                                                },
                                                "banner_2x": {
                                                    "type": "string"
                                                },
                                                "banner_3x": {
                                                    "type": "string"
                                                },
                                                "banner_4x": {
                                                    "type": "string"
                                                },
                                                "thumb_1x": {
                                                    "type": "string"
                                                },
                                                "thumb_2x": {
                                                    "type": "string"
                                                },
                                                "thumb_3x": {
                                                    "type": "string"
                                                },
                                                "thumb_4x": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            },
                            "gridColumn": {
                                "type": "integer"
                            },
                            "subscription": {},
                            "view_group_type": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "response.ViewGroupMockResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "children": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "action": {
                                            "type": "object",
                                            "properties": {
                                                "api": {
                                                    "type": "string"
                                                },
                                                "destination": {
                                                    "type": "string"
                                                },
                                                "method": {
                                                    "type": "string"
                                                },
                                                "query": {
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "background_color": {
                                            "type": "object",
                                            "properties": {
                                                "alpha": {
                                                    "type": "integer"
                                                },
                                                "hue": {
                                                    "type": "integer"
                                                },
                                                "lighting": {
                                                    "type": "integer"
                                                },
                                                "saturation": {
                                                    "type": "integer"
                                                }
                                            }
                                        },
                                        "product_id": {
                                            "type": "string"
                                        },
                                        "product_info": {
                                            "type": "object",
                                            "properties": {
                                                "display_selling_scale": {
                                                    "type": "string"
                                                },
                                                "offer_percentage": {
                                                    "type": "string"
                                                },
                                                "offer_price": {
                                                    "type": "integer"
                                                },
                                                "quantity": {
                                                    "type": "integer"
                                                },
                                                "unit_price": {
                                                    "type": "integer"
                                                }
                                            }
                                        },
                                        "subscription_info": {
                                            "type": "object",
                                            "properties": {
                                                "created_at": {
                                                    "type": "string"
                                                },
                                                "end_date": {
                                                    "type": "string"
                                                },
                                                "friday": {
                                                    "type": "boolean"
                                                },
                                                "monday": {
                                                    "type": "boolean"
                                                },
                                                "order_id": {
                                                    "type": "string"
                                                },
                                                "pause_dates": {
                                                    "type": "string"
                                                },
                                                "product_id": {
                                                    "type": "string"
                                                },
                                                "saturday": {
                                                    "type": "boolean"
                                                },
                                                "start_date": {
                                                    "type": "string"
                                                },
                                                "subscription_id": {
                                                    "type": "string"
                                                },
                                                "sunday": {
                                                    "type": "boolean"
                                                },
                                                "thursday": {
                                                    "type": "boolean"
                                                },
                                                "tuesday": {
                                                    "type": "boolean"
                                                },
                                                "user_id": {
                                                    "type": "string"
                                                },
                                                "wednesday": {
                                                    "type": "boolean"
                                                }
                                            }
                                        },
                                        "title": {
                                            "type": "string"
                                        },
                                        "type": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "object",
                                            "properties": {
                                                "banner_1x": {
                                                    "type": "string"
                                                },
                                                "banner_2x": {
                                                    "type": "string"
                                                },
                                                "banner_3x": {
                                                    "type": "string"
                                                },
                                                "banner_4x": {
                                                    "type": "string"
                                                },
                                                "thumb_1x": {
                                                    "type": "string"
                                                },
                                                "thumb_2x": {
                                                    "type": "string"
                                                },
                                                "thumb_3x": {
                                                    "type": "string"
                                                },
                                                "thumb_4x": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            },
                            "gridColumn": {
                                "type": "integer"
                            },
                            "header": {
                                "type": "object",
                                "properties": {
                                    "action": {
                                        "type": "object",
                                        "properties": {
                                            "api": {
                                                "type": "string"
                                            },
                                            "destination": {
                                                "type": "string"
                                            },
                                            "method": {
                                                "type": "string"
                                            },
                                            "query": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "background_color": {
                                        "type": "object",
                                        "properties": {
                                            "alpha": {
                                                "type": "integer"
                                            },
                                            "hue": {
                                                "type": "integer"
                                            },
                                            "lighting": {
                                                "type": "integer"
                                            },
                                            "saturation": {
                                                "type": "integer"
                                            }
                                        }
                                    },
                                    "ctaTitle": {
                                        "type": "string"
                                    },
                                    "title": {
                                        "type": "string"
                                    },
                                    "type": {
                                        "type": "string"
                                    }
                                }
                            },
                            "view_group_type": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "subscriptions.Subscription": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "friday": {
                    "type": "boolean"
                },
                "monday": {
                    "type": "boolean"
                },
                "order_id": {
                    "description": "This is OrderItemId",
                    "type": "string"
                },
                "pauseDates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "product": {
                    "$ref": "#/definitions/products.Product"
                },
                "product_id": {
                    "type": "string"
                },
                "saturday": {
                    "type": "boolean"
                },
                "startDate": {
                    "type": "string"
                },
                "subscription_id": {
                    "type": "string"
                },
                "sunday": {
                    "type": "boolean"
                },
                "thursday": {
                    "type": "boolean"
                },
                "tuesday": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                },
                "wednesday": {
                    "type": "boolean"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "login_mode": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "userData.BodyCreateUserInput": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "login_mode": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "userData.BodyUserIdInput": {
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "userData.BodyWishlistInput": {
            "type": "object",
            "required": [
                "productId",
                "quantity",
                "userId"
            ],
            "properties": {
                "productId": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "userData.StatusMsg": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "wishlist.Wishlist": {
            "type": "object",
            "properties": {
                "Created_at": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                },
                "wishlist_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.77.101:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "APIs of E-Commerce Project",
	Description:      "This is E-Commerce API Server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
