basePath: /
definitions:
  userData.CreateUserIdInput:
    properties:
      userId:
        type: string
    required:
    - userId
    type: object
  wishlist.Wishlist:
    properties:
      Created_at:
        type: string
      product_id:
        type: string
      quantity:
        type: integer
      user_id:
        type: string
      wishlist_id:
        type: string
    type: object
host: 192.168.13.5:8080
info:
  contact:
    email: support@swagger.io
    name: API Support (Ashwani)
    url: http://www.swagger.io/support
  description: This is E-Commerce API Server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: APIs of E-Commerce Project
  version: "1.0"
paths:
  /get_wishlist:
    post:
      consumes:
      - application/json
      description: Get the all wishlist of the User.
      parameters:
      - description: Request Body to get all Wishlist
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/userData.CreateUserIdInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/wishlist.Wishlist'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Shows the all wishlist of the User.
      tags:
      - User
  /wishlist:
    delete:
      consumes:
      - application/json
      description: To delete the selected product from User's Wishlist.
      parameters:
      - description: Query string, wishlist_id value
        in: query
        name: wishlistId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/wishlist.Wishlist'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Deletes the selected wishlistId from the Wishlist Table.
      tags:
      - User
schemes:
- http
swagger: "2.0"
